// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDxLFsB-4lxqxX6ddi9ypuwRY1F64cEZk4",
    authDomain: "image-drive-5e1c2.firebaseapp.com",
    projectId: "image-drive-5e1c2",
    storageBucket: "image-drive-5e1c2.appspot.com",
    messagingSenderId: "299380329166",
    appId: "1:299380329166:web:2710708fbfe0e08ed69e9f",
    measurementId: "G-D82KD19J5G",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB597BWi0WW8AUcLB4bQotwlflhGp5vbu0',
    appId: '1:299380329166:android:5202061bcb792d8ad69e9f',
    messagingSenderId: '299380329166',
    projectId: 'image-drive-5e1c2',
    storageBucket: 'image-drive-5e1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkkJttrBmr2NcVtWDVCKhbvGCYpF4rHE',
    appId: '1:299380329166:ios:d36e56f20dd893afd69e9f',
    messagingSenderId: '299380329166',
    projectId: 'image-drive-5e1c2',
    storageBucket: 'image-drive-5e1c2.appspot.com',
    iosBundleId: 'com.example.imageDrive',
  );
}
